#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/../build/"

cmake -DCMAKE_CXX_COMPILER="/usr/bin/clang++" -DCMAKE_C_COMPILER="/usr/bin/clang" -DCMAKE_CXX_FLAGS="-W -Werror -Wall -pedantic -Wconversion -Wextra -Wpedantic -Wshadow -fdiagnostics-color=always" ..

cmake --build .
